[package]
name = "suit-updatable"
edition.workspace = true
license.workspace = true
publish = false


[dependencies]
ariel-os = { workspace = true, features = ["coap", "defmt", "i2c", "random"] }

ariel-os-bindings = { workspace = true, features = ["log", "rng", "time"] }

coap-handler = "0.2.0"
coap-handler-implementations = "0.6.1"
coap-message = "0.3.2"
# error_title allows sending out messages; error_request_body_error_position
# would also be welcome, but so far I don't think wasmtime exports that (plus
# it probably take a lot of source map magic to make real use of it).
coap-message-utils = { version = "0.3.0", features = ["error_title"] }
coap-numbers = "0.2"
coap-request = "0.2.0-alpha.2"
coap-request-implementations = "0.1.0-alpha.4"

cose-nostd = { git = "https://codeberg.org/COLORADIO-Project/cose-nostd.git", rev = "59053ef78916ff038858b45fdd73ed9389c303f1", features = ["sign1", "p-256", "verify"] }

dress-up = { git = "https://github.com/ariel-os/dress-up", rev = "52c06ec6847fb9e60e09cb6a91cab73702db953b" }

embassy-futures = { version = "0.1.1", default-features = false }
embassy-sync = { version = "0.7.2" }
embedded-nal-coap = "=0.1.0-alpha.5"

generic-array = { version = "1.4.1", default-features = false }

rand_core = { workspace = true }

uuid = { version = "1.23.1", default-features = false, features = ["v5"] }

wasmtime = { workspace = true, default-features = false, features = [
  "async",
  "component-model",
  "pulley",
  "runtime",
] }

[lints]
workspace = true
