[unstable]
#build-std = ["core", "alloc", "panic_abort"]
#build-std-features = ["panic_immediate_abort"]

[build]
rustflags = [
    # "-Clinker=wasm-ld",
    "-Clink-arg=--page-size=1",
    "-Clink-arg=--initial-memory=30000",
    "-Clink-arg=-zstack-size=4496",
    "-Cpanic=abort",
]
target = "wasm32v1-none"