name: Payload building

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rebuild-cwasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dtolnay/rust-toolchain@master
        with:
          # The pinned nightly of Ariel OS v0.5.0
          toolchain: nightly-2026-04-28
          components: rust-src
        # This is needed for the .cargo/config.toml's include directive to work
        # In real application this file would come from the ariel os repo that
        # laze copies locally.
      - name: Create dummy cargo config
        run: |
          mkdir -p build/imports/ariel-os
          touch build/imports/ariel-os/ariel-os-cargo.toml

      - name: Install wasm-tools
        uses: taiki-e/install-action@74e87cbfa15a59692b158178d8905a61bf6fca95 # v2
        with:
          tool: wasm-tools@1.246.0
      - run: ./rebuild-all-payloads.sh
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          path: examples/*/*.cwasm
      - run: git diff --exit-code
