name: Payload building

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rebuild-cwasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          # The pinned nightly of Ariel OS v0.4.0
          toolchain: nightly-2026-01-20
          components: rust-src
        # This is needed for the .cargo/config.toml's include directive to work
        # In real application this file would come from the ariel os repo that
        # laze copies locally.
      - name: Create dummy cargo config
        run: |
          mkdir -p build/imports/ariel-os
          touch build/imports/ariel-os/ariel-os-cargo.toml

      - uses: taiki-e/install-action@v1
        with:
          tool: wasm-tools
      - run: ./rebuild-all-payloads.sh
      - uses: actions/upload-artifact@v4
        with:
          path: examples/*/*.cwasm
      - run: git diff --exit-code
